# Site
name: "Fanny's blog"
title: "Fanny's blog"
description: "Réflexions, tips et retours d'expérience d'une Accompagnatrice agile & DevOps"
logo: 'assets/images/logo.jpg'
favicon: 'assets/images/favicon.ico'
baseurl: /blog
#google_analytics: 'UA-xxxxxxxx-1'
disqus: 'demowebsite'
#mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/
email: klaukf@gmail.com

# Authors
authors:
  fanny:
    name: Fanny
    display_name: Fanny
    avatar: 'assets/images/logo.jpg'
    email: klaukf@gmail.com
    web: https://klaukf.github.io/blog/
    twitter: https://twitter.com/klf37
    bluesky: https://bsky.app/profile/klf37.bsky.social
    description: "Accompagnatrice agile & DevOps, co-créatrice de TADx, maman, amoureuse, adore les chouchous."
 
# Plugins - ne pas toucher
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
